# site settings
title: That guy with the Bucket List
# subtitle: by HTML5 UP
email: yuvankiran91@gmail.com
description: A blog of all the places I have visited
baseurl: "/travel" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kiran Jayaramu
# street_address: 1234 Somewhere Road
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url: https://www.facebook.com/yuvankiran
github_url: https://github.com/kiranj91
# gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+KiranJayaramu
instagram_url: https://www.instagram.com/narik_j
linkedin_url: https://www.linkedin.com/in/kiran-jayaram-68450370
pinterest_url:
slack_url:
# twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
